### ISSUE TITLE
Server crash and corrupts when right clicking translocator with item

### ISSUE THREAD

**Issue by KraiiFox** [TheCBProject/Translocators#58] opened 2018-12-21 09:49 UTC
Not sure if its related to #47 but ill report it anyways just in case.

https://pastebin.com/ggjrXM0X

Playing Stoneblock ver 1.0.31 on a dedicated server

**Comment by covers1624** [comment] 2019-01-02 06:36
Yes, this is a duplicate of #47

**Closed as completed by covers1624** 2019-01-02 06:36 UTC
